apiVersion: v1
kind: Template
parameters:
- name: REGISTRY_IMG
  required: true
- name: CHANNEL
  required: true
- name: IMAGE_TAG
  required: true
- name: IMAGE_DIGEST
  required: true
- name: REPO_NAME
  value: custom-domains-operator
  required: true
metadata:
  name: selectorsyncset-template
objects:
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    labels:
      managed.openshift.io/gitHash: ${IMAGE_TAG}
      managed.openshift.io/gitRepoName: ${REPO_NAME}
      managed.openshift.io/osd: 'true'
    name: custom-domains-operator
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: 'true'
      matchExpressions:
        - key: ext-managed.openshift.io/legacy-ingress-support
          operator: NotIn
          values: ["false"]
        - key: hive.openshift.io/version-major-minor
          operator: NotIn
          values: ["4.5", "4.6", "4.7", "4.8", "4.9", "4.10", "4.11", "4.12"]
    resourceApplyMode: Sync
    resources:
    - kind: Namespace
      apiVersion: v1
      metadata:
        name: openshift-custom-domains-operator
        labels:
          openshift.io/cluster-monitoring: 'true'
          pod-security.kubernetes.io/enforce: 'baseline'
          pod-security.kubernetes.io/audit: 'baseline'
          pod-security.kubernetes.io/warn: 'baseline'
    - apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      metadata:
        labels:
          opsrc-datastore: "true"
          opsrc-provider: redhat
        name: custom-domains-operator-registry
        namespace: openshift-custom-domains-operator
      spec:
        image: ${REGISTRY_IMG}@${IMAGE_DIGEST}
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: node-role.kubernetes.io/infra
                  operator: Exists
              weight: 1
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/infra
            operator: Exists
        displayName: Custom Domains Operator
        icon:
          base64data: ''
          mediatype: ''
        publisher: Red Hat
        sourceType: grpc
        grpcPodConfig:
          securityContextConfig: restricted
          nodeSelector:
            node-role.kubernetes.io: infra
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/infra
            operator: Exists
    - apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: custom-domains-operator
        namespace: openshift-custom-domains-operator
      spec:
        channel: ${CHANNEL}
        name: custom-domains-operator
        source: custom-domains-operator-registry
        sourceNamespace: openshift-custom-domains-operator
    - apiVersion: operators.coreos.com/v1alpha2
      kind: OperatorGroup
      metadata:
        name: custom-domains-operator
        namespace: openshift-custom-domains-operator
        annotations:
          olm.operatorframework.io/exclude-global-namespace-resolution: 'true'
      spec:
        targetNamespaces:
        - openshift-custom-domains-operator
